### ISSUE TITLE
Allow "validate_docstring" to take arguments for further filtering

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/testimony#10]
Generating a huge report can sometimes be a bit too much if you only want to see certain types of results. For instance, you may want to see only the tests that have missing docstrings. Sometimes, seeing the entire report is fine too.

Could we add a few options to ```validate_docstring``` to allow for further filtering? e.g. ```--all``` (default?), ```---missing```

**Comment by sthirugn** [comment]
validate command evolved in the last two years and now, it looks like - http://testimony-qe.readthedocs.io/en/latest/#validate-command.

Although the updated command does not let you drill down the results, it gives a nice picture of things. I am closing this issue for now.  Please feel free to reopen with more info, if necessary.
