### ISSUE TITLE
Improve token parser

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/testimony#120]
Currently the token parser relies on a regex, that helps but the current regex have an issue if the prefix token is present on the value of the token then that will not produce a valid match and will be skipped.

A good source or input data to test the token parser would be the same test data used to test RST field list parser [1]. Also maybe we can use the docutils parser to get the information Testimony needs.

Follows the data I was able to find the issue:

``` python
In [16]: s = """IDM-IPA-TC IPA Betelgeuse Example 0001
    ...: 
    ...: :ID:
    ...: 
    ...: IDM-IPA-TC: IPA Betelgeuse Example 0001
    ...: 
    ...: More lines comes here
    ...: 
    ...: :description: Description of the test
    ...: """
```

I've used the ID token, but it could be any other.

[1] https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/test/test_parsers/test_rst/test_field_lists.py

**Comment by droideck** [comment]
I work on it. I plan to use docutils parser that creates 'document' type: http://docutils.sourceforge.net/docs/ref/doctree.html

After this I will extract tokens and its values from it.

**Comment by elyezer** [comment]
@droideck thank you very much!

**Comment by elyezer** [comment]
This is already implemented, closing it.
