### ISSUE TITLE
values with colons not parsed correctly.

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/testimony#126]
Colons in value of a label in docstring appear to cause problems with parsing the value.

Does not seem to work:

`:description: http://something.gitrepo.test/some/path`

Seems to work:

`:description: something.gitrepo.test/some/path`

See more details in betelgeuse issue here:

https://github.com/SatelliteQE/betelgeuse/issues/92

**Comment by elyezer** [comment]
I've observed that the XML generated by the docutils parser is a little dependent of the contents of the docstring, for example with a first line paragraph it generates a field_list:

```
In [6]: parser.parse("""Text
   ...: 
   ...: :description: Something before http://test.com/path/to/something, something after
   ...: 
   ...: :bz: something
   ...: """)
b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">\n<!-- Generated by Docutils 0.12 -->\n<document source="&lt;string&gt;"><paragraph>Text</paragraph><field_list><field><field_name>description</field_name><field_body><paragraph>Something before <reference refuri="http://test.com/path/to/something">http://test.com/path/to/something</reference>, something after</paragraph></field_body></field><field><field_name>bz</field_name><field_body><paragraph>something</paragraph></field_body></field></field_list></document>'
Out[6]: ({}, {})
```

But without the first line paragraph it generates the field elements inside a docinfo:

```
In [5]: parser.parse(""":description: Something before http://test.com/path/to/something, something after
   ...: 
   ...: :bz: something
   ...: """)
b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">\n<!-- Generated by Docutils 0.12 -->\n<document source="&lt;string&gt;"><docinfo><field><field_name>description</field_name><field_body><paragraph>Something before <reference refuri="http://test.com/path/to/something">http://test.com/path/to/something</reference>, something after</paragraph></field_body></field><field><field_name>bz</field_name><field_body><paragraph>something</paragraph></field_body></field></docinfo></document>'
Out[5]: ({}, {})
```

Need to find a more reliable way to parse the tokens.

**Comment by spoore1** [comment]
Also, with the latest checked in version in github, I'm not seeing the tokens returned like I do with the version installed from pypi with pip.  With the latest from github, I'm only seeing this:

# cat dir4/test_feature4.py 

class TestFeature4(object):
    def test_feature4_0001(self):
        """ MY-TEST- feature4- test 1
        :id: my-test.feature4.test_1
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa 
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass

    def test_feature4_0002(self):
        """ MY-TEST- feature4- test 2
        :id: my-test.feature4.test_2
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa 
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass

    def test_feature4_0003(self):
        """ MY-TEST- feature4- test 3
        :id: my-test.feature4.test_3
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa 
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass

# echo $TOKENS
requirement,caselevel,casecomponent,caseautomation,caseimportance,testtype,description,title,id,expectedresults,setup,steps

# echo $MINIMUM 
requirement,casecomponent,title
(FYI, I trimmed some of the whitespace below to make it a little easier to read here)

# testimony --tokens $TOKENS --minimum-tokens $MINIMUM print dir4/test_feature4.py 
dir4/test_feature4.py
=====================
test_feature4_0001
------------------
Test:
 MY-TEST- feature4- test 1

test_feature4_0002
------------------
Test:
 MY-TEST- feature4- test 2

test_feature4_0003
------------------
Test:
 MY-TEST- feature4- test 3

With the version from pypi though, I see the all the tokens output.   Is this also related to the xml parsing?

**Comment by elyezer** [comment]
Before we used a Regular Expression to do the parsing, then we started using docutils RST parser. The version available on master is using the docutils parser and that said it is not parsing because it is thinking that you have a single paragraph, you need to have a blank line between the first line and the tokens (or field-list).

The regex did not require valid RST to be written but now it does which ensure we follow the Python's documentation standards we see out there. Even sphinx won't be able to generate a field list without the blank line.

You can check the difference using http://rst.ninjs.org/ for example. Without the blank line in between it will not generate the field list.

**Comment by elyezer** [comment]
I had a try and got the following:

```
$ cat test_feature4.py 
class TestFeature4(object):
    def test_feature4_0001(self):
        """ MY-TEST- feature4- test 1

        :id: my-test.feature4.test_1
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass

    def test_feature4_0002(self):
        """ MY-TEST- feature4- test 2

        :id: my-test.feature4.test_2
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass

    def test_feature4_0003(self):
        """ MY-TEST- feature4- test 3

        :id: my-test.feature4.test_3
        :requirement: My Feature 0004
        :caselevel: Acceptance
        :casecomponent: ipa
        :caseautomation: Automated
        :caseimportance: Medium
        :testtype: Functional
        :description: someurl/src/package/dir4
        """
        pass


$ testimony --tokens requirement,caselevel,casecomponent,caseautomation,caseimportance,testtype,description,title,id,expectedresults,setup,steps --minimum-tokens requirement,casecomponent,title print test_feature4.py
test_feature4.py
================

test_feature4_0001
------------------

Caseautomation:
 Automated

Casecomponent:
 ipa

Caseimportance:
 Medium

Caselevel:
 Acceptance

Description:
 someurl/src/package/dir4

Id:
 my-test.feature4.test_1

Requirement:
 My Feature 0004

Test:
 MY-TEST- feature4- test 1

Testtype:
 Functional


test_feature4_0002
------------------

Caseautomation:
 Automated

Casecomponent:
 ipa

Caseimportance:
 Medium

Caselevel:
 Acceptance

Description:
 someurl/src/package/dir4

Id:
 my-test.feature4.test_2

Requirement:
 My Feature 0004

Test:
 MY-TEST- feature4- test 2

Testtype:
 Functional


test_feature4_0003
------------------

Caseautomation:
 Automated

Casecomponent:
 ipa

Caseimportance:
 Medium

Caselevel:
 Acceptance

Description:
 someurl/src/package/dir4

Id:
 my-test.feature4.test_3

Requirement:
 My Feature 0004

Test:
 MY-TEST- feature4- test 3

Testtype:
 Functional
```

**Comment by elyezer** [comment]
It seems that I've found a solution for this, other than xml the `publish_string` accepts `writer_name` as html which, guess what, will produce HTML output. The HTML output will create a table which we can inspect and get the value of the tokens as HTML which should preserve any formatting done. I will play more with that later, will update here if I found something.

**Comment by spoore1** [comment]
Yep, the blank line worked.   Also, adding `:` to the first line titles worked.  However, I got a failure when adding a url to description:
`
# testimony --tokens $TOKENS --minimum-tokens $MINIMUM print dir4/test_feature4.py 
dir4/test_feature4.py
=====================

Traceback (most recent call last):
  File "/usr/bin/testimony", line 9, in <module>
    load_entry_point('testimony==1.2.0-', 'console_scripts', 'testimony')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/testimony/cli.py", line 26, in testimony
    main(report, path, json, nocolor)
  File "/usr/lib/python2.7/site-packages/testimony/__init__.py", line 168, in main
    sys.exit(report_function(get_testcases(paths)))
  File "/usr/lib/python2.7/site-packages/testimony/__init__.py", line 187, in print_report
    test.name, '-' * len(test.name), test))
  File "/usr/lib/python2.7/site-packages/testimony/__init__.py", line 137, in __str__
    token.capitalize(), indent(value, ' ')))
  File "/usr/lib/python2.7/site-packages/testimony/__init__.py", line 55, in indent
    return ''.join(prefixed_lines())
  File "/usr/lib/python2.7/site-packages/testimony/__init__.py", line 53, in prefixed_lines
    for line in text.splitlines(True):
AttributeError: 'NoneType' object has no attribute 'splitlines'
`
When I prepended the url with a backslash though, it works.  So, I guess in RST that is what I want in order to have it processed like a string.

**Comment by elyezer** [comment]
@spoore1 that is related to parsing the html I mentioned on the previous comment. I happens if you don't have any text on the value a child xml tag will be added (called `reference`). To fix that immediately we can call `itertext` on the element. But I think the final solution using HTML will 1) be more robust 2) preserve any formatting present on the docstring.

**Comment by elyezer** [comment]
There is another function called `publish_parts` that could also be useful since it is one of the recommended ways to programmatically extract information from the parsed text. From the docs [1]:

> publish_parts: for programmatic use with string input; returns a dictionary of document parts. Dictionary keys are the names of parts, and values are Unicode strings; encoding is up to the client. Useful when only portions of the processed document are desired. See publish_parts Details below.

[1] http://docutils.sourceforge.net/docs/api/publisher.html

**Comment by elyezer** [comment]
Another interesting point is:

> When a field list is the first non-comment element in a document (after the document title, if there is one), it may have its fields transformed to document bibliographic data. This bibliographic data corresponds to the front matter of a book, such as the title page and copyright page.

Source: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bibliographic-fields

**Comment by spoore1** [comment]
So, could we use bibliographic-fields to work around the issue with defining a url as a value?

**Comment by mbukatov** [comment]
Just a note: process noted in https://github.com/SatelliteQE/testimony/issues/126#issuecomment-287460071 is implemented by [DocInfo transformation](http://repo.or.cz/docutils.git/blob/HEAD:/docutils/docutils/transforms/frontmatter.py#l288).

**Comment by elyezer** [comment]
> So, could we use bibliographic-fields to work around the issue with defining a url as a value?

@spoore1 we need to check if the element is either docinfo or field-list. Then we should consider both to get the information. Also we need to grab the entire value of each field because right now it is only getting the first element text and if the first element is a link the URL is not properly returned.

**Comment by elyezer** [comment]
@mbukatov thanks for the information. Do you know if we can configure the parser to avoid the transformations?

I will check and reply here if I find something. But I am going to do that on Monday.

**Comment by mbukatov** [comment]
@elyezer Yes, you need to create your own reader and drop the transformation there:

```
from docutils.readers import standalone
from docutils.transforms import frontmatter


class NoDocInfoReader(standalone.Reader):
    """
    NoDocInfoReader extends docutils standalone ReStructuredText reader
    to drop DocInfo transformation, everything else remains the same.
    """

    def get_transforms(self):
        transforms = standalone.Reader.get_transforms(self)
        transforms.remove(frontmatter.DocInfo)
        return transforms
```

**Comment by elyezer** [comment]
@mbukatov thank you very much! Will get this done today.

**Comment by elyezer** [comment]
My current work in progress branch to fix this is available at https://github.com/SatelliteQE/testimony/compare/master...elyezer:fix-126
