### ISSUE TITLE
support reading docstrings from package __init__.py files

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/testimony#127]
adding ticket to support `__init__.py` docstrings per Betelgeuse issue conversation here:

https://github.com/SatelliteQE/betelgeuse/issues/97

Agreed to start with supporting package `__init__.py` and will initially only support reading `__init__.py` docstrings for modules within its directory.

I should be submitting a pull request soon for this for review.

**Comment by elyezer** [comment]
Related PR is merged, this can be closed.
