### ISSUE TITLE
Release new version of testimony

### ISSUE THREAD

**Issue by mirzal** [SatelliteQE/testimony#147]
Can we release new version of testimony, to bring improved JSON structure to PyPI users?

**Comment by elyezer** [comment]
@mirzal you are a maintainer, wanna try making your first release?

**Comment by mirzal** [comment]
Was easier than I expected :) .
Fixed in 094e578708a616e86b11f77addc3554f9fc5a5d9 . 2.1.0 is available on PyPI, GitHub also lists it in versions.
