### ISSUE TITLE
Provide Finer-grained ability to see test case coverage.

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/testimony#52]
There have been inferences that we should be able to see, in greater detail, what our test cases in the automation system entail.  I agree that this would be a good next step for reporting.

It would print the name of the file containing cases, followed by a list of the "title" within the docstrings for each case.  We could also append [AUTO] or [MANUAL] to the end of each title, as well.

Something like

<code>testimony --list-cases</code>

<pre>
Analyzing test_orgs.py...
Cases:
   Enter a valid alphanumeric org name   [AUTO]
   Delete an org [AUTO]
   Create an org with the name of an org previously deleted [MANUAL]
...

Analyzing test_users.py...
Cases:
   Enter a valid alphanumeric username [AUTO]
   Enter a username that is too long  [AUTO]
   Attempt to login with user that has been deleted [MANUAL]
...

</pre>

...and so forth.
We could also return total counts at the end of each suite, as well

<pre>
   Total # of cases: xxx
   Total # of automated cases: xxx
   Total # of manual cases: xxx
</pre>

If we wanted to be fancy, it'd be nice to be able to colorize and right justify the AUTO/MANUAL reference on each line so that things look clean, but that's just eye candy.

An optional sort by auto/manual status might be nice too.

**Comment by elyezer** [comment]
I think this issue can be closed, the summary report seems to be covering the proposed idea.

**Comment by sthirugn** [comment]
Closing this issue as per the previous comment. Please reopen with more info, if necessary.
