### ISSUE TITLE
Proposal: Improve testimony cli

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/testimony#79]
Testimony is growing and more features are being added and are planned to land soon. Currently argparser module is being used, but is recommended to use Click which provides more power and easy way to grow.

**Comment by Ichimonji10** [comment]
I've not used click personally. But I spent some time teaching myself about the library, and it seems *very* well put together. Also, anything made by Armin Ronacher is worth paying attention to.

**Comment by sthirugn** [comment]
:+1:
