### ISSUE TITLE
Release a new testimony version

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/testimony#88]
The version currently on PyPI is breaking Betelgeuse, that said we need a new version of Testimony with the latest updates on master.

**Comment by elyezer** [comment]
@sthirugn I am. But the issue is from new comers, had someone interested on Betelguese who have installed it from PyPI, because that I'm requesting a new version in order to avoid the issue with others.

**Comment by sthirugn** [comment]
v 1.0.5 is now released to pypi

**Comment by elyezer** [comment]
@sthirugn thank you very much. :tada:
