### ISSUE TITLE
Support test case steps for import

### ISSUE THREAD

**Issue by spoore1** [SatelliteQE/testimony#92]
Can betelgeuse be updated to parse and write test case steps into step fields instead of the description?

**Comment by spoore1** [comment]
This one is somewhat related to this:
https://github.com/SatelliteQE/testimony/issues/90
Can see how that one gets implemented to determine how to handle this if that is better for the team.

**Comment by Akasurde** [comment]
@spoore1 Betelgeuse can import test case steps. here is the [PR](https://github.com/SatelliteQE/betelgeuse/pull/33)

**Comment by sthirugn** [comment]
There is no change needed from testimony side and this should be a new issue for betelgeuse.

**Comment by spoore1** [comment]
Ah, ok, yes, I meant to open this for Betelgeuse.  I'm closing this one.
